// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    A: typeof import('./src/components/Mitt/A.vue')['default']
    B: typeof import('./src/components/Mitt/B.vue')['default']
    CustomBread: typeof import('./src/components/CustomBread/index.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    Layout: typeof import('./src/components/Layout/Layout.vue')['default']
    Recursion: typeof import('./src/components/Recursion/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TestPinia: typeof import('./src/components/TestPinia/index.vue')['default']
    TestSlot: typeof import('./src/components/TestSlot/TestSlot.vue')['default']
    TestSuspense: typeof import('./src/components/TestSuspense/index.vue')['default']
  }
}
